
FROM python:3.6
RUN pip install --upgrade pip
RUN pip install Django==3.1.1
RUN pip install django-extensions==3.0.8
RUN pip install psycopg2-binary==2.8.6
RUN pip install django-cors-headers==3.5.0
RUN pip install ipython

WORKDIR /app
